/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_lpadc.h"
#include "fsl_lpi2c.h"
#include "fsl_spc.h"
#include "fsl_vref.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Alias for ADC1 peripheral */
#define ADC1_PERIPHERAL ADC1
/* BOARD_InitPeripherals defines for LP_FLEXCOMM2 */
/* Definition of peripheral ID */
#define LP_FLEXCOMM2_PERIPHERAL LPI2C2
/* Definition of peripheral base address */
#define LP_FLEXCOMM2_PERIPHERAL_BASE LPI2C2_BASE
/* Definition of the clock source frequency */
#define LP_FLEXCOMM2_CLOCK_SOURCE 12000000UL
/* Alias for ADC0 peripheral */
#define ADC0_PERIPHERAL ADC0
/* Definition of peripheral ID */
#define VREF0_PERIPHERAL VREF0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpadc_config_t ADC1_config;
extern lpadc_conv_command_config_t ADC1_commandsConfig[1];
extern lpadc_conv_trigger_config_t ADC1_triggersConfig[1];
extern const lpi2c_master_config_t LP_FLEXCOMM2_masterConfig;
extern const lpadc_config_t ADC0_config;
extern lpadc_conv_command_config_t ADC0_commandsConfig[1];
extern lpadc_conv_trigger_config_t ADC0_triggersConfig[1];

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
